var data = [{
        name: "大侦探",
        src: "img/1.jpg",
        time: "00:00",
        yy: "英语3D",
        dizhi: "9号激光厅",
        mon: "42",
    },
    {
        name: "阿达啥大事多",
        src: "img/2.jpg",
        time: "21:09",
        yy: "英语3D",
        dizhi: "9号激光厅",
        mon: "20",
    },
    {
        name: "大叔",
        src: "img/3.jpg",
        time: "15:21",
        yy: "英语3D",
        dizhi: "9号激光厅",
        mon: "10",
    },
    {
        name: "大撒啊",
        src: "img/4.jpg",
        time: "01：69",
        yy: "英语3D",
        dizhi: "9号激光厅",
        mon: "30",
    },
    {
        name: "大萨达",
        src: "img/5.jpg",
        time: "00:05",
        yy: "英语3D",
        dizhi: "9号激光厅",
        mon: "50",
    },
    {
        name: "大叔",
        src: "img/1.jpg",
        time: "21：36",
        yy: "英语3D",
        dizhi: "9号激光厅",
        mon: "100",
    },
    {
        name: "发放",
        src: "img/2.jpg",
        time: "20:30",
        yy: "英语3D",
        dizhi: "9号激光厅",
        mon: "20",
    }
]